name: SpotDL Workflow

on:
  workflow_dispatch:
    inputs:
      spotify_url:
        description: "URL de la canción o playlist de Spotify"
        required: true
        default: "https://open.spotify.com/playlist/20qc2TEShaQKMutv8qb1gf"

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      # Checkout del repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # Configuración de Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # Instalar FFmpeg
      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      # Instalación de SpotDL
      - name: Install SpotDL
        run: |
          pip install spotdl

      # Descargar la playlist
      - name: Download music
        run: |
          spotdl ${{ inputs.spotify_url }}

      # Subir las canciones como artefacto
      - name: Upload MP3s
        uses: actions/upload-artifact@v3
        with:
          name: downloaded-music
          path: "*.mp3"
