name: SpotDL Workflow

on:
  workflow_dispatch:
    inputs:
      spotify_url:
        description: "URL de la canción o playlist de Spotify"
        required: true
        default: "https://open.spotify.com/track/4VqPOruhp5EdPBeR92t6lQ"

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      # Checkout del repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # Configuración de Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # Instalar FFmpeg
      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      # Actualizar YT-DLP
      - name: Upgrade YT-DLP
        run: |
          pip install --upgrade yt-dlp

      # Reinstalar SpotDL
      - name: Reinstall SpotDL
        run: |
          pip install --upgrade spotdl

      # Descargar la canción/playlist con logs detallados
      - name: Download music with debug logs
        run: |
          spotdl --log-level DEBUG ${{ inputs.spotify_url }} 2>&1 | tee spotdl.log

      # Subir las canciones como artefactos
      - name: Upload MP3s
        uses: actions/upload-artifact@v3
        with:
          name: downloaded-music
          path: "*.mp3"
        if: success()

      # Subir los logs como artefactos
      - name: Upload logs
        uses: actions/upload-artifact@v3
        with:
          name: spotdl-logs
          path: spotdl.log
