name: SpotDL Automation

on:
  workflow_dispatch: # Permite ejecutar manualmente el flujo
  push:              # Ejecutar cuando haya un nuevo commit en la rama principal
    branches:
      - main

jobs:
  run-spotdl:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install SpotDL
      run: |
        pip install poetry
        poetry install

    - name: Run SpotDL command
      run: |
        # Ejemplo: descarga una lista de reproducción en MP3
        poetry run spotdl --playlist https://open.spotify.com/intl-es/track/7CkJfQByYyFdu9jRRXk858?si=46286191d9fa4dd6
