name: SpotDL Workflow

on:
  workflow_dispatch:  # Permite iniciar manualmente el workflow

jobs:
  download_song:
    runs-on: ubuntu-latest

    steps:
    # Configurar el repositorio
    - name: Checkout repository
      uses: actions/checkout@v3

    # Configurar Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Versión compatible con SpotDL

    # Instalar spotDL y sus dependencias
    - name: Install dependencies
      run: |
        pip install spotdl
        sudo apt-get update && sudo apt-get install -y ffmpeg

    # Descargar canción usando SpotDL
    - name: Download song
      run: |
        mkdir -p downloaded_songs
        spotdl "https://open.spotify.com/intl-es/track/1Rj5fXGOrfFpynoO19Xtar?si=82302379bb844833" --output downloaded_songs/

    # Subir los archivos descargados como artefacto de GitHub Actions
    - name: Upload downloaded songs
      uses: actions/upload-artifact@v3
      with:
        name: downloaded-songs
        path: downloaded_songs/
